server:
  port: 8082
spring:
datasource:
driver-class-name: oracle.jdbc.driver.OracleDriver
password: tiger
url: jdbc:oracle:thin:@localhost:1521/orcl
username: scott
jpa:
 properties:
  hibernate:
   format_sql: true
   show_sql: true
   hibernate:
   ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
      servlet:
      context-path: /register

